# Generated by Django 5.0.2 on 2024-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('JS', 'Job Seeker'), ('CO', 'Company')], max_length=2, null=True),
        ),
    ]
