# Generated by Django 5.0.2 on 2024-02-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_education_skill_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='job_seeker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.jobseeker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='job_seeker',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.jobseeker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='job_seeker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='accounts.jobseeker'),
            preserve_default=False,
        ),
    ]
