# Generated by Django 5.0.2 on 2024-02-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_education_job_seeker_skill_job_seeker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('people_to_hire', models.PositiveSmallIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('published_at', models.DateField(auto_now_add=True)),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('job_type', models.CharField(choices=[('F', 'Full time'), ('I', 'Intern ship'), ('C', 'Contract'), ('R', 'Remote')], max_length=1)),
                ('deadline', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.company')),
            ],
        ),
    ]
